Remove unused test_suite() that now causes unittest and pytest warnings

diff --git a/supervisor/tests/cutomer_logger/messages b/supervisor/tests/cutomer_logger/messages
--- a/supervisor/tests/cutomer_logger/messages
+++ b/supervisor/tests/cutomer_logger/messages
@@ -1,17 +1,7 @@
 #!/bin/bash
 
-while true; do
-  current_second=$(date +%S)
-  if [ "$current_second" -ge 45 ]; then
-    for i in {0..20000}; do
-      echo Test $i
-      sleep 0.0001
-      echo "Test error $i" >&2
-    done
-    break
-  else
-    echo "wait exec $current_second"
-    echo "wait exec $current_second" >&2
-    sleep 1
-  fi
+for i in {0..30}; do
+  echo Test $i
+  sleep 1
+  echo "Test error $i" >&2
 done
